# SwiftLint Configuration for Swift 6

# Swift version
swift_version: "6.0"

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length  # We'll configure this separately

# Opt-in rules for Swift 6 and best practices
opt_in_rules:
  # Performance
  - empty_count
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - sorted_first_last
  
  # Clarity
  - explicit_init
  - joined_default_parameter
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - yoda_condition
  
  # Safety
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - legacy_random
  - unavailable_function
  
  # Code Organization
  - closure_spacing
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  
  # Override
  - overridden_super_call
  - prohibited_super_call
  
  # Access Control
  - lower_acl_than_parent
  - private_action
  - private_outlet
  - strict_fileprivate

# Excluded paths
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Pods
  - Carthage
  - build
  - Package.resolved

# Line length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Type body length
type_body_length:
  warning: 300
  error: 400

# Function body length
function_body_length:
  warning: 50
  error: 100

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Nesting
nesting:
  type_level: 2
  function_level: 3

# Identifier naming
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ID
    - url
    - URL
    - uri
    - URI
    - to
    - db
    - at
    - on
    - os
    - ttl
    - key
    - raw

# Type name
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - URL
    - URI
    - ID

# Custom rules
custom_rules:
  # Require explicit Sendable conformance comments
  sendable_comment:
    name: "Sendable Conformance"
    regex: '@unchecked Sendable'
    match_kinds:
      - comment
    message: "Use @unchecked Sendable carefully and document why it's safe"
    severity: warning

# Analyzer rules (requires compilation)
analyzer_rules:
  - unused_declaration
  - unused_import
